name: bspwm
version: 0.9.5
summary: bspwm window manger.
description: A tiling window manager based on binary space partitioning with a focus on resource efficiency.
  
adopt-info:awesome

grade: stable
confinement: devmode

architectures:
  - build-on: amd64

apps:
    bspwm:
    command: bash
        slots: [mir, upower-observe]
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - network-manager
        - udisks2
      
slots:
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 
   -dbus:
        interface: dbus
        bus: session
        name: 
    -dbus:
        interface: dbus
        bus: session
        name: 

parts:
  bspwm:
        stage-packages: [bspwm-workspace-wayland, bspwm, gdb, strace, vim, wayland-backend-x11, libxkbcommon-x11-0, libxkbcommon0, libx11-data, xkb-data, ltrace]
        plugin: dump
        source: empty
        organize:
            usr/bin/Xwayland: usr/bin/Xwayland.orig
    patchy:
        after: [bspwm]
        plugin: dump
        source: xwayland
        
   - on amd64: https://http.us.debian.org/debian/bspwm_0.9.5-1_amd64.deb
    source-type: deb
    override-build: |
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        DEB_API="https://http.us.debian.org/debian/bspwm_0.9.5-1_amd64.deb"
      else
        echo "ERROR!bspwm only produces debs for i386 or amd64. Failing the build here."
        exit 1
      fi
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'_' -f2)
      echo $VERSION > $SNAPCRAFT_STAGE/version
      
      snapcraftctl build
    build-packages:
      - curl
      - dpkg
      - sed
    stage-packages:
     - dbus-session-bus  
     - gir1.2-freedesktop
     - gir1.2-gdkpixbuf-2.0
     - gir1.2-glib-2.0       
     - gir1.2-pango-1.0      
     - libc6      
     - libcairo-gobject2       
     - libcairo2        
     - libdbus-1-3        
     - libgdk-pixbuf2.0-0 
     - libglib2.0-0 
     - liblua5.3-0
     - libstartup-notification0      
     - libx11-6      
     - libxcb-cursor0 
     - libxcb-icccm4
     - libxcb-keysyms1 
     - libxcb-randr0 
     - libxcb-shape0
     - libxcb-util1 
     - libxcb-xinerama0     
     - libxcb-xkb1
     - libxcb-xrm0 
     - libxcb-xtest0        
     - libxcb1 
     - libxdg-basedir1       
     - libxkbcommon-x11-0
     - libxkbcommon0 
     - lua-lgi 
     - menu     
     - feh 
     - gir1.2-gtk-3.0     
     - rlwrap 
     - x11-xserver-utils
     - awesome-doc 
